'use strict';

var timerStart = Game.getUsedCpu();

// Autogenerated code
require('_generated');

var controller = require('stage_controller');
var creeps = require('stage_creeps');
var spawners = require('stage_spawners');

var timerRequire = Game.getUsedCpu();

controller.pre();
var timerPreController = Game.getUsedCpu();

creeps();
var timerCreeps = Game.getUsedCpu();

spawners();
var timerSpawners = Game.getUsedCpu();

controller.post();
var timerEnd = Game.getUsedCpu();

if (timerEnd > AI.settings.roundTimeLimit) {
    var message = '';
    message += "Round " + Game.time + "\n";
    message += Game.cpuLimit === Infinity ? "" : (Math.round(timerEnd / Game.cpuLimit * 100) + "% of cpu budget used.\n");
    message += "Currently " + AI.getTimeDiff(0, timerEnd) + " ms used";
    message += Game.cpuLimit === Infinity ? "\n" : " (of " + Game.cpuLimit + " ms available)\n";
    message += "Start           " + AI.getTimeDiff(0, timerStart) + " ms\n";
    message += "Requiring       " + AI.getTimeDiff(timerStart, timerRequire) + " ms\n";
    message += "Pre controller  " + AI.getTimeDiff(timerRequire, timerPreController) + " ms\n";
    message += "Creeps          " + AI.getTimeDiff(timerPreController, timerCreeps) + " ms\n";
    message += "Spawners        " + AI.getTimeDiff(timerCreeps, timerSpawners) + " ms\n";
    message += "Post controller " + AI.getTimeDiff(timerSpawners, timerEnd) + " ms\n";
    message += "After end       " + AI.getTimeDiff(timerEnd, Game.getUsedCpu()) + " ms\n";
    console.log(message);
}